### PR TITLE
Upgrade to .net8

### PR DESCRIPTION
**Pull request by gcaracuel**
This PR requires Elenpay/NBXplorer#9

### CODE REVIEW

**Comment by gcaracuel** [comment]
We are running this in STG via Elenpay/platform#732 and deployed via this branch

**Review by Jossec101 — CHANGES_REQUESTED** [review]
Hm, this is NGMI, you would need also to update all the `ASP Net Core` packages to dotnet 8

**Comment by Jossec101** [comment]
> We are running this in STG via [Elenpay/platform#732](https://github.com/Elenpay/platform/pull/732) and deployed via this branch

Does this hack fix it then?

**Comment by gcaracuel** [comment]
> > We are running this in STG via [Elenpay/platform#732](https://github.com/Elenpay/platform/pull/732) and deployed via this branch
> 
> Does this hack fix it then?

Seems so, it does compile and runs. It does not differ much from https://github.com/dgarage/NBXplorer/blob/master/NBXplorer/NBXplorer.csproj 
I could update those things that we have introduced like OpenTelemetry but net8 is supported in the current version also.

**Comment by Jossec101** [comment]
@RodriFS @gcaracuel #10 closes this?

**Comment by gcaracuel** [comment]
> @RodriFS @gcaracuel #10 closes this?

Yes, @RodriFS 's new PR takes care of this in the proper way

**Pull request closed without merging**
